// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 9/3/2025, 12:00:34 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/Users/swiz/Desktop/uni/web/nuxt/web-portal/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/swiz/Desktop/uni/web/nuxt/web-portal/app/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/swiz/Desktop/uni/web/nuxt/web-portal/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/swiz/Desktop/uni/web/nuxt/web-portal/app/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/swiz/Desktop/uni/web/nuxt/web-portal/app/plugins/**/*.{js,ts,mjs}","/Users/swiz/Desktop/uni/web/nuxt/web-portal/app/composables/**/*.{js,ts,mjs}","/Users/swiz/Desktop/uni/web/nuxt/web-portal/app/utils/**/*.{js,ts,mjs}","/Users/swiz/Desktop/uni/web/nuxt/web-portal/app/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/swiz/Desktop/uni/web/nuxt/web-portal/app/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/swiz/Desktop/uni/web/nuxt/web-portal/app/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;